[features]
seeds = false
skip-lint = false

[programs.localnet]
settleflow_escrow = "6ExqVZTvHUERDa7JjY8kHs1NDfZD1woAN4ovkmSsrePK"

[programs.devnet]
settleflow_escrow = "6ExqVZTvHUERDa7JjY8kHs1NDfZD1woAN4ovkmSsrePK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
