[features]
seeds = false
skip-lint = false

[programs.localnet]
settleflow_escrow = "Fg6PaFpoGXkYsidMpWxTWq3nx5pYQ5zL2q6T7qWtXrJ4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
